name: Unit Tests

on: [push, pull_request]

env:
  CI: true

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: CultureHQ/actions-yarn@master
        with:
          args: install
      - uses: CultureHQ/actions-yarn@master
        with:
          args: test
